github: anicmarko9
custom: "Your support makes a difference! 🌟 By sponsoring me, you're not just backing my projects; you're investing in innovation and the open-source community. Together, we can shape the future of technology. Join me on this exciting journey, and let's make amazing things happen. Thank you for being a part of my work! 💙"
